// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ride/ride.proto

// import "google/protobuf/empty.proto";

package ride

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int64                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      uint64                 `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRideRequest) Reset() {
	*x = AcceptRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRideRequest) ProtoMessage() {}

func (x *AcceptRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRideRequest.ProtoReflect.Descriptor instead.
func (*AcceptRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptRideRequest) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *AcceptRideRequest) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type Ride struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PassengerId       int64                  `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId          *int64                 `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3,oneof" json:"driver_id,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Pickup            *Location              `protobuf:"bytes,5,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination       *Location              `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	EstimatedDistance float64                `protobuf:"fixed64,7,opt,name=estimated_distance,json=estimatedDistance,proto3" json:"estimated_distance,omitempty"`
	EstimatedDuration int32                  `protobuf:"varint,8,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	RequestedAt       string                 `protobuf:"bytes,9,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	DriverAssignedAt  string                 `protobuf:"bytes,10,opt,name=driver_assigned_at,json=driverAssignedAt,proto3" json:"driver_assigned_at,omitempty"`
	DriverArrivedAt   string                 `protobuf:"bytes,11,opt,name=driver_arrived_at,json=driverArrivedAt,proto3" json:"driver_arrived_at,omitempty"`
	StartedAt         string                 `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt       string                 `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CancelledAt       string                 `protobuf:"bytes,14,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ride) Reset() {
	*x = Ride{}
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ride) ProtoMessage() {}

func (x *Ride) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ride.ProtoReflect.Descriptor instead.
func (*Ride) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{1}
}

func (x *Ride) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ride) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *Ride) GetDriverId() int64 {
	if x != nil && x.DriverId != nil {
		return *x.DriverId
	}
	return 0
}

func (x *Ride) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ride) GetPickup() *Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *Ride) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Ride) GetEstimatedDistance() float64 {
	if x != nil {
		return x.EstimatedDistance
	}
	return 0
}

func (x *Ride) GetEstimatedDuration() int32 {
	if x != nil {
		return x.EstimatedDuration
	}
	return 0
}

func (x *Ride) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

func (x *Ride) GetDriverAssignedAt() string {
	if x != nil {
		return x.DriverAssignedAt
	}
	return ""
}

func (x *Ride) GetDriverArrivedAt() string {
	if x != nil {
		return x.DriverArrivedAt
	}
	return ""
}

func (x *Ride) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Ride) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Ride) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

func (x *Ride) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ride) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickup        *Location              `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination   *Location              `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	VehicleType   string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	PassengerID   int64                  `protobuf:"varint,4,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRideRequest) Reset() {
	*x = CreateRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequest) ProtoMessage() {}

func (x *CreateRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequest.ProtoReflect.Descriptor instead.
func (*CreateRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRideRequest) GetPickup() *Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *CreateRideRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *CreateRideRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateRideRequest) GetPassengerID() int64 {
	if x != nil {
		return x.PassengerID
	}
	return 0
}

type RideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ride          *Ride                  `protobuf:"bytes,1,opt,name=ride,proto3" json:"ride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RideResponse) Reset() {
	*x = RideResponse{}
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideResponse) ProtoMessage() {}

func (x *RideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideResponse.ProtoReflect.Descriptor instead.
func (*RideResponse) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{4}
}

func (x *RideResponse) GetRide() *Ride {
	if x != nil {
		return x.Ride
	}
	return nil
}

type CancelRideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        int64                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,2,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideRequest) Reset() {
	*x = CancelRideRequest{}
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideRequest) ProtoMessage() {}

func (x *CancelRideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ride_ride_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideRequest.ProtoReflect.Descriptor instead.
func (*CancelRideRequest) Descriptor() ([]byte, []int) {
	return file_proto_ride_ride_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRideRequest) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *CancelRideRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

var File_proto_ride_ride_proto protoreflect.FileDescriptor

const file_proto_ride_ride_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ride/ride.proto\x12\vrideService\"I\n" +
	"\x11AcceptRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x03R\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x04R\bdriverId\"\xe7\x04\n" +
	"\x04Ride\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fpassenger_id\x18\x02 \x01(\x03R\vpassengerId\x12 \n" +
	"\tdriver_id\x18\x03 \x01(\x03H\x00R\bdriverId\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12-\n" +
	"\x06pickup\x18\x05 \x01(\v2\x15.rideService.LocationR\x06pickup\x127\n" +
	"\vdestination\x18\x06 \x01(\v2\x15.rideService.LocationR\vdestination\x12-\n" +
	"\x12estimated_distance\x18\a \x01(\x01R\x11estimatedDistance\x12-\n" +
	"\x12estimated_duration\x18\b \x01(\x05R\x11estimatedDuration\x12!\n" +
	"\frequested_at\x18\t \x01(\tR\vrequestedAt\x12,\n" +
	"\x12driver_assigned_at\x18\n" +
	" \x01(\tR\x10driverAssignedAt\x12*\n" +
	"\x11driver_arrived_at\x18\v \x01(\tR\x0fdriverArrivedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\f \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\r \x01(\tR\vcompletedAt\x12!\n" +
	"\fcancelled_at\x18\x0e \x01(\tR\vcancelledAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_driver_id\"^\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xc0\x01\n" +
	"\x11CreateRideRequest\x12-\n" +
	"\x06pickup\x18\x01 \x01(\v2\x15.rideService.LocationR\x06pickup\x127\n" +
	"\vdestination\x18\x02 \x01(\v2\x15.rideService.LocationR\vdestination\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12 \n" +
	"\vpassengerID\x18\x04 \x01(\x03R\vpassengerID\"5\n" +
	"\fRideResponse\x12%\n" +
	"\x04ride\x18\x01 \x01(\v2\x11.rideService.RideR\x04ride\"O\n" +
	"\x11CancelRideRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x03R\x06rideId\x12!\n" +
	"\fcancelled_by\x18\x02 \x01(\tR\vcancelledBy2\xe8\x01\n" +
	"\vRideService\x12G\n" +
	"\n" +
	"CreateRide\x12\x1e.rideService.CreateRideRequest\x1a\x19.rideService.RideResponse\x12G\n" +
	"\n" +
	"AcceptRide\x12\x1e.rideService.AcceptRideRequest\x1a\x19.rideService.RideResponse\x12G\n" +
	"\n" +
	"CancelRide\x12\x1e.rideService.CancelRideRequest\x1a\x19.rideService.RideResponseB\x13Z\x11./shared/pkg/rideb\x06proto3"

var (
	file_proto_ride_ride_proto_rawDescOnce sync.Once
	file_proto_ride_ride_proto_rawDescData []byte
)

func file_proto_ride_ride_proto_rawDescGZIP() []byte {
	file_proto_ride_ride_proto_rawDescOnce.Do(func() {
		file_proto_ride_ride_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)))
	})
	return file_proto_ride_ride_proto_rawDescData
}

var file_proto_ride_ride_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ride_ride_proto_goTypes = []any{
	(*AcceptRideRequest)(nil), // 0: rideService.AcceptRideRequest
	(*Ride)(nil),              // 1: rideService.Ride
	(*Location)(nil),          // 2: rideService.Location
	(*CreateRideRequest)(nil), // 3: rideService.CreateRideRequest
	(*RideResponse)(nil),      // 4: rideService.RideResponse
	(*CancelRideRequest)(nil), // 5: rideService.CancelRideRequest
}
var file_proto_ride_ride_proto_depIdxs = []int32{
	2, // 0: rideService.Ride.pickup:type_name -> rideService.Location
	2, // 1: rideService.Ride.destination:type_name -> rideService.Location
	2, // 2: rideService.CreateRideRequest.pickup:type_name -> rideService.Location
	2, // 3: rideService.CreateRideRequest.destination:type_name -> rideService.Location
	1, // 4: rideService.RideResponse.ride:type_name -> rideService.Ride
	3, // 5: rideService.RideService.CreateRide:input_type -> rideService.CreateRideRequest
	0, // 6: rideService.RideService.AcceptRide:input_type -> rideService.AcceptRideRequest
	5, // 7: rideService.RideService.CancelRide:input_type -> rideService.CancelRideRequest
	4, // 8: rideService.RideService.CreateRide:output_type -> rideService.RideResponse
	4, // 9: rideService.RideService.AcceptRide:output_type -> rideService.RideResponse
	4, // 10: rideService.RideService.CancelRide:output_type -> rideService.RideResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_ride_ride_proto_init() }
func file_proto_ride_ride_proto_init() {
	if File_proto_ride_ride_proto != nil {
		return
	}
	file_proto_ride_ride_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ride_ride_proto_rawDesc), len(file_proto_ride_ride_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ride_ride_proto_goTypes,
		DependencyIndexes: file_proto_ride_ride_proto_depIdxs,
		MessageInfos:      file_proto_ride_ride_proto_msgTypes,
	}.Build()
	File_proto_ride_ride_proto = out.File
	file_proto_ride_ride_proto_goTypes = nil
	file_proto_ride_ride_proto_depIdxs = nil
}
