syntax="proto3";

import "google/protobuf/empty.proto";

package driverService;
option go_package = "./shared/pkg/driver";



service DriverService {
    rpc Register(CreateRequestDriver) returns (UserResponse);
    rpc Login(LoginUserRequest) returns (UserResponse);
    rpc Self(google.protobuf.Empty) returns (UserSelfResponse);
    rpc Logout(google.protobuf.Empty) returns(google.protobuf.Empty);
    rpc Refresh(google.protobuf.Empty) returns (UserResponse);
}

service VehicleService {
    rpc Create(CreateRequestVehicle) returns (VehicleResponse);
    rpc Update(UpdateRequestVehicle) returns (VehicleResponse);
    // rpc Delete(google.protobuf.Empty) returns(DeleteResponse);
    // rpc GetByID(google.protobuf.Empty) returns(VehicleResponse);
    // rpc GetAll(google.protobuf.Empty) returns(VehicleResponse);
}

message Vehicle{
     int64 id = 1;
     int64 userId = 2;
     string fullName = 3;
     string plateNumber = 4;
     bool  status = 5;
}


message CreateRequestVehicle{
     int64 userId = 1;
     string fullName = 2;
     string plateNumber = 3;
     bool status = 4;
}

message UpdateRequestVehicle{
     string fullName = 2;
     string plateNumber = 3;
     bool status = 4;
}
message DeleteResponse {
    string message = 1;
}

message VehicleResponse {
    Vehicle vehicle = 1;
}

message Driver {
     int64 id = 1;
     string fullname = 2;
     string email = 3;
     string phone = 4;
     string role = 5;
}

message CreateRequestDriver{
    string fullname = 1;
    string email = 2;
     string phone = 3;
    string password = 4;
    string role = 5;
}
message UpdateRequestDriver{
    string fullname = 1;
    string email = 2;
    string phone = 3;
    string password = 4;
    string role = 5;
    int64 id = 6;
}

message LoginUserRequest{
   string email = 1;
   string password = 2;
}


message UserResponse{
Driver diver = 1;
string access_token = 2;
string refresh_token = 3;
}

message UserSelfResponse{
    uint64 id = 1;
     string fullname = 2;
    string email = 3;
    string phone = 4;
    string role = 5;
}