// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DriverId      uint64                 `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateDriverLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetDriverId() uint64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type DriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLocationResponse) Reset() {
	*x = DriverLocationResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLocationResponse) ProtoMessage() {}

func (x *DriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLocationResponse.ProtoReflect.Descriptor instead.
func (*DriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *DriverLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,4,opt,name=plateNumber,proto3" json:"plateNumber,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Vehicle) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Vehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *Vehicle) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type CreateRequestVehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,3,opt,name=plateNumber,proto3" json:"plateNumber,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestVehicle) Reset() {
	*x = CreateRequestVehicle{}
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestVehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestVehicle) ProtoMessage() {}

func (x *CreateRequestVehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestVehicle.ProtoReflect.Descriptor instead.
func (*CreateRequestVehicle) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequestVehicle) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRequestVehicle) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateRequestVehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *CreateRequestVehicle) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateRequestVehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,3,opt,name=plateNumber,proto3" json:"plateNumber,omitempty"`
	Status        bool                   `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestVehicle) Reset() {
	*x = UpdateRequestVehicle{}
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestVehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestVehicle) ProtoMessage() {}

func (x *UpdateRequestVehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestVehicle.ProtoReflect.Descriptor instead.
func (*UpdateRequestVehicle) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRequestVehicle) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateRequestVehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *UpdateRequestVehicle) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleResponse) Reset() {
	*x = VehicleResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleResponse) ProtoMessage() {}

func (x *VehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleResponse.ProtoReflect.Descriptor instead.
func (*VehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{6}
}

func (x *VehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_driver_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{7}
}

func (x *Driver) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Driver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *Driver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Driver) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Driver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateRequestDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestDriver) Reset() {
	*x = CreateRequestDriver{}
	mi := &file_proto_driver_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestDriver) ProtoMessage() {}

func (x *CreateRequestDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestDriver.ProtoReflect.Descriptor instead.
func (*CreateRequestDriver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRequestDriver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *CreateRequestDriver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRequestDriver) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateRequestDriver) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateRequestDriver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRequestDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestDriver) Reset() {
	*x = UpdateRequestDriver{}
	mi := &file_proto_driver_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestDriver) ProtoMessage() {}

func (x *UpdateRequestDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestDriver.ProtoReflect.Descriptor instead.
func (*UpdateRequestDriver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRequestDriver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UpdateRequestDriver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateRequestDriver) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRequestDriver) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRequestDriver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateRequestDriver) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{10}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diver         *Driver                `protobuf:"bytes,1,opt,name=diver,proto3" json:"diver,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{11}
}

func (x *UserResponse) GetDiver() *Driver {
	if x != nil {
		return x.Diver
	}
	return nil
}

func (x *UserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type UserSelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSelfResponse) Reset() {
	*x = UserSelfResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSelfResponse) ProtoMessage() {}

func (x *UserSelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSelfResponse.ProtoReflect.Descriptor instead.
func (*UserSelfResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{12}
}

func (x *UserSelfResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSelfResponse) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserSelfResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSelfResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSelfResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\rdriverService\x1a\x1bgoogle/protobuf/empty.proto\"t\n" +
	"\x1bUpdateDriverLocationRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\x04R\bdriverId\"2\n" +
	"\x16DriverLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfullName\x18\x03 \x01(\tR\bfullName\x12 \n" +
	"\vplateNumber\x18\x04 \x01(\tR\vplateNumber\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"\x84\x01\n" +
	"\x14CreateRequestVehicle\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12 \n" +
	"\vplateNumber\x18\x03 \x01(\tR\vplateNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"l\n" +
	"\x14UpdateRequestVehicle\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12 \n" +
	"\vplateNumber\x18\x03 \x01(\tR\vplateNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\bR\x06status\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\x0fVehicleResponse\x120\n" +
	"\avehicle\x18\x01 \x01(\v2\x16.driverService.VehicleR\avehicle\"t\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x8d\x01\n" +
	"\x13CreateRequestDriver\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x9d\x01\n" +
	"\x13UpdateRequestDriver\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x83\x01\n" +
	"\fUserResponse\x12+\n" +
	"\x05diver\x18\x01 \x01(\v2\x15.driverService.DriverR\x05diver\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"~\n" +
	"\x10UserSelfResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role2\xc3\x03\n" +
	"\rDriverService\x12K\n" +
	"\bRegister\x12\".driverService.CreateRequestDriver\x1a\x1b.driverService.UserResponse\x12E\n" +
	"\x05Login\x12\x1f.driverService.LoginUserRequest\x1a\x1b.driverService.UserResponse\x12?\n" +
	"\x04Self\x12\x16.google.protobuf.Empty\x1a\x1f.driverService.UserSelfResponse\x128\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\aRefresh\x12\x16.google.protobuf.Empty\x1a\x1b.driverService.UserResponse\x12c\n" +
	"\x0eUpdateLocation\x12*.driverService.UpdateDriverLocationRequest\x1a%.driverService.DriverLocationResponse2\xae\x01\n" +
	"\x0eVehicleService\x12M\n" +
	"\x06Create\x12#.driverService.CreateRequestVehicle\x1a\x1e.driverService.VehicleResponse\x12M\n" +
	"\x06Update\x12#.driverService.UpdateRequestVehicle\x1a\x1e.driverService.VehicleResponseB\x15Z\x13./shared/pkg/driverb\x06proto3"

var (
	file_proto_driver_driver_proto_rawDescOnce sync.Once
	file_proto_driver_driver_proto_rawDescData []byte
)

func file_proto_driver_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)))
	})
	return file_proto_driver_driver_proto_rawDescData
}

var file_proto_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_driver_driver_proto_goTypes = []any{
	(*UpdateDriverLocationRequest)(nil), // 0: driverService.UpdateDriverLocationRequest
	(*DriverLocationResponse)(nil),      // 1: driverService.DriverLocationResponse
	(*Vehicle)(nil),                     // 2: driverService.Vehicle
	(*CreateRequestVehicle)(nil),        // 3: driverService.CreateRequestVehicle
	(*UpdateRequestVehicle)(nil),        // 4: driverService.UpdateRequestVehicle
	(*DeleteResponse)(nil),              // 5: driverService.DeleteResponse
	(*VehicleResponse)(nil),             // 6: driverService.VehicleResponse
	(*Driver)(nil),                      // 7: driverService.Driver
	(*CreateRequestDriver)(nil),         // 8: driverService.CreateRequestDriver
	(*UpdateRequestDriver)(nil),         // 9: driverService.UpdateRequestDriver
	(*LoginUserRequest)(nil),            // 10: driverService.LoginUserRequest
	(*UserResponse)(nil),                // 11: driverService.UserResponse
	(*UserSelfResponse)(nil),            // 12: driverService.UserSelfResponse
	(*emptypb.Empty)(nil),               // 13: google.protobuf.Empty
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	2,  // 0: driverService.VehicleResponse.vehicle:type_name -> driverService.Vehicle
	7,  // 1: driverService.UserResponse.diver:type_name -> driverService.Driver
	8,  // 2: driverService.DriverService.Register:input_type -> driverService.CreateRequestDriver
	10, // 3: driverService.DriverService.Login:input_type -> driverService.LoginUserRequest
	13, // 4: driverService.DriverService.Self:input_type -> google.protobuf.Empty
	13, // 5: driverService.DriverService.Logout:input_type -> google.protobuf.Empty
	13, // 6: driverService.DriverService.Refresh:input_type -> google.protobuf.Empty
	0,  // 7: driverService.DriverService.UpdateLocation:input_type -> driverService.UpdateDriverLocationRequest
	3,  // 8: driverService.VehicleService.Create:input_type -> driverService.CreateRequestVehicle
	4,  // 9: driverService.VehicleService.Update:input_type -> driverService.UpdateRequestVehicle
	11, // 10: driverService.DriverService.Register:output_type -> driverService.UserResponse
	11, // 11: driverService.DriverService.Login:output_type -> driverService.UserResponse
	12, // 12: driverService.DriverService.Self:output_type -> driverService.UserSelfResponse
	13, // 13: driverService.DriverService.Logout:output_type -> google.protobuf.Empty
	11, // 14: driverService.DriverService.Refresh:output_type -> driverService.UserResponse
	1,  // 15: driverService.DriverService.UpdateLocation:output_type -> driverService.DriverLocationResponse
	6,  // 16: driverService.VehicleService.Create:output_type -> driverService.VehicleResponse
	6,  // 17: driverService.VehicleService.Update:output_type -> driverService.VehicleResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
		MessageInfos:      file_proto_driver_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
