// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Driver) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Driver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *Driver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Driver) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *Driver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateRequestDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestDriver) Reset() {
	*x = CreateRequestDriver{}
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestDriver) ProtoMessage() {}

func (x *CreateRequestDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestDriver.ProtoReflect.Descriptor instead.
func (*CreateRequestDriver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequestDriver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *CreateRequestDriver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateRequestDriver) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *CreateRequestDriver) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateRequestDriver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRequestDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         int64                  `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            int64                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestDriver) Reset() {
	*x = UpdateRequestDriver{}
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestDriver) ProtoMessage() {}

func (x *UpdateRequestDriver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestDriver.ProtoReflect.Descriptor instead.
func (*UpdateRequestDriver) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequestDriver) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UpdateRequestDriver) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateRequestDriver) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *UpdateRequestDriver) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRequestDriver) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateRequestDriver) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diver         *Driver                `protobuf:"bytes,1,opt,name=diver,proto3" json:"diver,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponse) GetDiver() *Driver {
	if x != nil {
		return x.Diver
	}
	return nil
}

func (x *UserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_proto_driver_driver_proto protoreflect.FileDescriptor

const file_proto_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x19proto/driver/driver.proto\x12\rdriverService\x1a\x1bgoogle/protobuf/empty.proto\"t\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\x03R\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x8d\x01\n" +
	"\x13CreateRequestDriver\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\x03R\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x9d\x01\n" +
	"\x13UpdateRequestDriver\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\x03R\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x03R\x02id\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x83\x01\n" +
	"\fUserResponse\x12+\n" +
	"\x05diver\x18\x01 \x01(\v2\x15.driverService.DriverR\x05diver\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken2\xe0\x01\n" +
	"\rDriverService\x12K\n" +
	"\bRegister\x12\".driverService.CreateRequestDriver\x1a\x1b.driverService.UserResponse\x12E\n" +
	"\x05Login\x12\x1f.driverService.LoginUserRequest\x1a\x1b.driverService.UserResponse\x12;\n" +
	"\x04Self\x12\x16.google.protobuf.Empty\x1a\x1b.driverService.UserResponseB\x15Z\x13./shared/pkg/driverb\x06proto3"

var (
	file_proto_driver_driver_proto_rawDescOnce sync.Once
	file_proto_driver_driver_proto_rawDescData []byte
)

func file_proto_driver_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)))
	})
	return file_proto_driver_driver_proto_rawDescData
}

var file_proto_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_driver_driver_proto_goTypes = []any{
	(*Driver)(nil),              // 0: driverService.Driver
	(*CreateRequestDriver)(nil), // 1: driverService.CreateRequestDriver
	(*UpdateRequestDriver)(nil), // 2: driverService.UpdateRequestDriver
	(*LoginUserRequest)(nil),    // 3: driverService.LoginUserRequest
	(*UserResponse)(nil),        // 4: driverService.UserResponse
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_proto_driver_driver_proto_depIdxs = []int32{
	0, // 0: driverService.UserResponse.diver:type_name -> driverService.Driver
	1, // 1: driverService.DriverService.Register:input_type -> driverService.CreateRequestDriver
	3, // 2: driverService.DriverService.Login:input_type -> driverService.LoginUserRequest
	5, // 3: driverService.DriverService.Self:input_type -> google.protobuf.Empty
	4, // 4: driverService.DriverService.Register:output_type -> driverService.UserResponse
	4, // 5: driverService.DriverService.Login:output_type -> driverService.UserResponse
	4, // 6: driverService.DriverService.Self:output_type -> driverService.UserResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_driver_driver_proto_init() }
func file_proto_driver_driver_proto_init() {
	if File_proto_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_driver_proto_rawDesc), len(file_proto_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_driver_proto_depIdxs,
		MessageInfos:      file_proto_driver_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_driver_proto = out.File
	file_proto_driver_driver_proto_goTypes = nil
	file_proto_driver_driver_proto_depIdxs = nil
}
