// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/matching/matching.proto

package matching

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindDriverRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RideId          int64                  `protobuf:"varint,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	PickupLatitude  float64                `protobuf:"fixed64,2,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude float64                `protobuf:"fixed64,3,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	VehicleType     string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindDriverRequest) Reset() {
	*x = FindDriverRequest{}
	mi := &file_proto_matching_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDriverRequest) ProtoMessage() {}

func (x *FindDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDriverRequest.ProtoReflect.Descriptor instead.
func (*FindDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_matching_proto_rawDescGZIP(), []int{0}
}

func (x *FindDriverRequest) GetRideId() int64 {
	if x != nil {
		return x.RideId
	}
	return 0
}

func (x *FindDriverRequest) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *FindDriverRequest) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *FindDriverRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type FindDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDriverResponse) Reset() {
	*x = FindDriverResponse{}
	mi := &file_proto_matching_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDriverResponse) ProtoMessage() {}

func (x *FindDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDriverResponse.ProtoReflect.Descriptor instead.
func (*FindDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_matching_proto_rawDescGZIP(), []int{1}
}

func (x *FindDriverResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindDriverResponse) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

var File_proto_matching_matching_proto protoreflect.FileDescriptor

const file_proto_matching_matching_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/matching/matching.proto\x12\x0fmatchingService\"\xa3\x01\n" +
	"\x11FindDriverRequest\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\x03R\x06rideId\x12'\n" +
	"\x0fpickup_latitude\x18\x02 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x03 \x01(\x01R\x0fpickupLongitude\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\"G\n" +
	"\x12FindDriverResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId2h\n" +
	"\x0fMatchingService\x12U\n" +
	"\n" +
	"FindDriver\x12\".matchingService.FindDriverRequest\x1a#.matchingService.FindDriverResponseB\x17Z\x15./shared/pkg/matchingb\x06proto3"

var (
	file_proto_matching_matching_proto_rawDescOnce sync.Once
	file_proto_matching_matching_proto_rawDescData []byte
)

func file_proto_matching_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_matching_proto_rawDesc), len(file_proto_matching_matching_proto_rawDesc)))
	})
	return file_proto_matching_matching_proto_rawDescData
}

var file_proto_matching_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_matching_matching_proto_goTypes = []any{
	(*FindDriverRequest)(nil),  // 0: matchingService.FindDriverRequest
	(*FindDriverResponse)(nil), // 1: matchingService.FindDriverResponse
}
var file_proto_matching_matching_proto_depIdxs = []int32{
	0, // 0: matchingService.MatchingService.FindDriver:input_type -> matchingService.FindDriverRequest
	1, // 1: matchingService.MatchingService.FindDriver:output_type -> matchingService.FindDriverResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_matching_matching_proto_init() }
func file_proto_matching_matching_proto_init() {
	if File_proto_matching_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_matching_proto_rawDesc), len(file_proto_matching_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_matching_proto = out.File
	file_proto_matching_matching_proto_goTypes = nil
	file_proto_matching_matching_proto_depIdxs = nil
}
